version: '3.8'

services:
  tu-descartable-app-dev:
    image: node-point-sell-dev:1.0
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
      - ./public:/app/public
    ports:
      - '3004:3004'
    env_file:
      - .env
